site_name: PyOSC Documentation
site_url: https://theatre-tools.github.io/PyOSC/
theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
    annotation: material/arrow-right-circle

  features:
    - content.code.copy
    - content.code.select
    - content.action.view
    - content.action.edit
    - search.highlight
    - search.share
    - search.suggest
    - navigation.instant        # mini popups
    - navigation.top            # sticky nav
    - navigation.tracking       # highlights active page
    - navigation.instant.prefetch
    - navigation.instant.progress
    - content.tooltips
    - content.code.annotate

repo_url: https://github.com/theatre-tools/PyOSC
repo_name: theatre-tools/PyOSC
edit_uri: https://github.com/theatre-tools/PyOSC/tree/main/docs/
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: theatre-tools/PyOSC
      branch: main
  - search
  - privacy


copyright: >
  Copyright &copy; 2025 - 2026 Morph Tollon –
  <a href="#__consent">Change cookie settings</a>

extra:
  show_pre_release_warning: !ENV [MKDOCS_SHOW_PRE_RELEASE_WARNING, false]
  version:
    provider: mike
    default: stable
  generator: false
  analytics: 
    provider: google
    property: G-P6CRQR38Y9
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            creating a <a href="https://github.com/theatre-tools/PyOSC/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">github issue!</a>.

  consent:
    actions:
      - accept
      - reject
      - manage
    title: Cookie consent
    description: >- 
      We use cookies to make docuementation better. Nothing nefarious, nothing to make money. We simply use google analytics to see what pages are most popular, and to get a general sense of how people are using the documentation.
      You do have the right to easily reject the use of these cookies, which you can do by simply clicking "reject". However, please consider how usefull the information would be to us in improving the documentation.


markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
  - attr_list
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - .
        - docs
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - First Steps: getting-started/first-steps.md
  - Tutorials:
      - Creating a Peer: tutorials/peer.md
      - Sending Messages: tutorials/message.md
      - Receiving Messages: tutorials/dispatcher.md
      - Using Call Handlers: tutorials/call_handler.md
      - Using Event Handlers: tutorials/event_handler.md
  - API Reference: api_reference.md
  - Roadmap: roadmap.md
  - Contributing: contributing.md
  - Changelog: changelog.md
watch:
  - docs
  - CHANGELOG.md
